### ISSUE TITLE
CCminer 1.3.2 can't start on Ubuntu 20.04

### ISSUE THREAD

**Issue by Shekelme** [firoorg/ccminer#62]
When I'm trying to start ccminer 1.3.2, it return the error message as follows:

`./ccminer_linux_cuda100: error while loading shared libraries: libcudart.so.10.0: cannot open shared object file: No such file or directory`

Ubuntu 20.04, RTX 2080Ti, nVidia driver 440.100.

The same with ccminer_linux_cuda102:
`error while loading shared libraries: libcudart.so.10.2: cannot open shared object file: No such file or directory`

**Comment by hehh2001** [comment]
cuda版本不对

**Comment by ralyodio** [comment]
I get this error too. Anyone know how to fix?

**Comment by djm34** [comment]
you have to add to LD_LIBRARY_PATH the path to cuda libraries

**Comment by MrAn0nym** [comment]
> you have to add to LD_LIBRARY_PATH the path to cuda libraries

Ubuntu cuda 10.2 is not available for ubuntu 20.04

**Comment by djm34** [comment]
1min google search (please search a minimum before posting, there is no reason I google stuff for you)
https://medium.com/@stephengregory_69986/installing-cuda-10-1-on-ubuntu-20-04-e562a5e724a0

(not mentionning you can probably also use newer version (avoid 11.2, stay with 11.1 you do so)
