### ISSUE TITLE
custom flags

### ISSUE THREAD

**Issue by Goldinium** [firoorg/ccminer#63]
Hi 

it's not really an issue, however i don't find any documentation about the custom flags used on command line to launch ccminer

for example this 
strict,verbose,d=500 -i 20

what does "strict" do,  and d ? difficulty? and what about -i

thank you

**Comment by djm34** [comment]
these parameter are parameters which are passed to mintpond, you will probably find some explanation on mintpond website 
As far as I remember "strict" refer to how vardif will work, with strict and d=500 it will never adjust the difficulty such it goes below 500. 
i is the intensity of the miner
